### ISSUE TITLE
TypeError exception when running on the CERN VM (Python 2.6)

### ISSUE THREAD

**Issue by willfurnell** [calhewitt/lucid-utils#1]
Hi,
I'm getting the following error when I try and run lucid-utils analysis on the CERN VM.

``` python
Traceback (most recent call last):
  File "/cvmfs/researchinschools.egi.eu/software/grid-analysis//analyse.py", line 17, in <module>
    from lucid_utils.classification.old_algorithm import classify
  File "/cvmfs/lucid.egi.eu/libraries/python2.6/site-packages/lucid_utils/classification/old_algorithm.py", line 14, in <module>
    types = json.JSONDecoder(object_pairs_hook=OrderedDict).decode(open(os.path.dirname(os.path.realpath(__file__)) + "/types/old_algorithm.json").read())
TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'
```

It looks like that JSON feature isn't supported in Python 2.6 (https://github.com/circonus-labs/circonusvi/blob/master/README.md).
Is it possible to add support for simplejson when running with Python 2.6 please?

Thanks very much,

Will.

**Comment by calhewitt** [comment]
Hi Will,
I'll have a look at it now - shouldn't be too hard to fix! I think the only reason it was using an ordered dictionary in the first place was for trying to incorporate proton and muon counts into the CERN@school algorithm, which I eventually gave up on and used a different approach as the definitions were too close to that for beta to work accurately. So it might be good to enough to simply switch to the standard json decoder. I'm also trying to work out a more general solution to the slightly dodgy way in which libraries are working in general on the CVMFS, and the fact that Scientific Linux seems to be working only on Python 2.6 by default - no idea why they haven't updated in all this time!

Hopefully should be done soon!
Cal

**Comment by calhewitt** [comment]
Ok - have just reverted to using json.loads instead of the custom decoder and all seems to work fine. Let me know if there are any other problems!
Cal
